### DECLARING |0> AND |1>

In [2]:
import numpy as np
q0=np.array([[1],[0]])
q1=np.array([[0],[1]])
print("\nq0=\n",q0 )
print("\nq1=\n",q1)


q0=
 [[1]
 [0]]

q1=
 [[0]
 [1]]


### DECLARING UNITARY MATRIX AND HERMITIAN MATRIX

In [4]:
X = np.array([[0,1],[1, 0]])
print("X = \n",X)

X = 
 [[0 1]
 [1 0]]


In [6]:
hermitianMatrix = np.conj(X).transpose()
unitaryMatrix = np.matmul(X, hermitianMatrix)
print("unitaryMatrix: XX* =\n ",unitaryMatrix)
print("hermitianMatrix: if A* = A i.e,\nA =\n",X,"\nand A* =\n",hermitianMatrix,"\ntherefore we can conclude A=A*, therefore A is a Hermitian Matrix.")

unitaryMatrix: XX* =
  [[1 0]
 [0 1]]
hermitianMatrix: if A* = A i.e,
A =
 [[0 1]
 [1 0]] 
and A* =
 [[0 1]
 [1 0]] 
therefore we can conclude A=A*, therefore A is a Hermitian Matrix.


### INNER PRODUCT, OUTER PRODUCT AND TENSOR PRODUCT 

In [7]:
print("INNER PRODUCT")
F = np.array([2, 1-2j])
V = np.array([[1, 2]])
print("Inner product of F and V is\n",np.dot(V,np.conj(F).transpose()))

INNER PRODUCT
Inner product of F and V is
 [4.+4.j]


In [9]:
print("Outer Product of F and V is\n",np.outer(F,V))

Outer Product of F and V is
 [[2.+0.j 4.+0.j]
 [1.-2.j 2.-4.j]]


In [11]:
print("Tensor Product of \nV=\n", V,"\nand F =\n",F,"\nis =\n",np.tensordot(V,F,0))

Tensor Product of 
V=
 [[1 2]] 
and F =
 [2.+0.j 1.-2.j] 
is =
 [[[2.+0.j 1.-2.j]
  [4.+0.j 2.-4.j]]]


### QUANTUM GATES: PAULI-X(NOT), PAULI-Z, HADAMARD, CNOT, TOFFOLI 

In [12]:
print("PAULI-X Gate output when applied on state 0: \n",np.matmul(X, q0))
print("PAULI-X Gate output when applied on state 1: \n",np.matmul(X, q1))

PAULI-X Gate output when applied on state 0: 
 [[0]
 [1]]
PAULI-X Gate output when applied on state 1: 
 [[1]
 [0]]


In [13]:
print("PAULI Z-Gate")
Z = np.array([[1,0],[0, -1]])
print("When acted on state 0: \n|0>:\n",np.matmul(Z,q0))
print("When acted on state 1: \n|1>:\n",np.matmul(Z,q1))
print("Z- gate leaves |0 unchanged, and flips the sign of |1 to give −|1")

PAULI Z-Gate
When acted on state 0: 
|0>:
 [[1]
 [0]]
When acted on state 1: 
|1>:
 [[ 0]
 [-1]]
Z- gate leaves |0 unchanged, and flips the sign of |1 to give −|1


In [16]:
import math
print("HADAMARD GATE")
X1 = np.array([[1,0],[0,1]])
H = np.dot(1/math.sqrt(2),np.array([[1,1],[1,-1]]))
print("Output of the hadamard gate when applied to |0>:\n",np.matmul(H,q0))
print("Output of the hadamard gate when applied to |1>:\n",np.matmul(H,q1))

HADAMARD GATE
Output of the hadamard gate when applied to |0>:
 [[0.70710678]
 [0.70710678]]
Output of the hadamard gate when applied to |1>:
 [[ 0.70710678]
 [-0.70710678]]


In [19]:
print("CNOT GATE")
q00 = np.tensordot(q0,q0,0)
q01 = np.tensordot(q0,q1,0)
q10 = np.tensordot(q1,q0,0)
q11 = np.tensordot(q1,q1,0)
cnot = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
q10 = np.tensordot(q1,q0,0)
cnot.resize(4,4)
q10.resize(4,1)
q11.resize(4,1)
q00.resize(4,1)
q01.resize(4,1)
print("CNOT |00> =\n", np.matmul(cnot,q00))
print("CNOT |01> =\n",np.matmul(cnot,q01))
print("CNOT |10> =\n",np.matmul(cnot,q10))
print("CNOT |11> =\n",np.matmul(cnot,q11))

CNOT GATE
CNOT |00> =
 [[1]
 [0]
 [0]
 [0]]
CNOT |01> =
 [[0]
 [1]
 [0]
 [0]]
CNOT |10> =
 [[0]
 [0]
 [0]
 [1]]
CNOT |11> =
 [[0]
 [0]
 [1]
 [0]]


In [20]:
q000=np.tensordot(q00,q0,0)
q001=np.tensordot(q00,q1,0)
q010=np.tensordot(q01,q0,0)
q011=np.tensordot(q01,q1,0)
q100=np.tensordot(q10,q0,0)
q101=np.tensordot(q10,q1,0)
q110=np.tensordot(q11,q0,0)
q111=np.tensordot(q11,q1,0)
Toffoli = np.array([
            [1,0,0,0,0,0,0,0],
            [0,1,0,0,0,0,0,0],
            [0,0,1,0,0,0,0,0],
            [0,0,0,1,0,0,0,0],
            [0,0,0,0,1,0,0,0],
            [0,0,0,0,0,1,0,0],
            [0,0,0,0,0,0,0,1],
            [0,0,0,0,0,0,1,0]])
q000.resize(8,1)
q001.resize(8,1)
q010.resize(8,1)
q011.resize(8,1)
q100.resize(8,1)
q101.resize(8,1)
q110.resize(8,1)
q111.resize(8,1)
a = np.array([q000,q001,q010,q011,q100,q101,q110,q111])
av = np.array(["000","001","010","011","100","101","110","111"])
for i in range(0,8):
    print("Toffoli |",av[i],"> =\n",np.matmul(Toffoli,a[i]))

Toffoli | 000 > =
 [[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
Toffoli | 001 > =
 [[0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
Toffoli | 010 > =
 [[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
Toffoli | 011 > =
 [[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]]
Toffoli | 100 > =
 [[0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]]
Toffoli | 101 > =
 [[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]]
Toffoli | 110 > =
 [[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]
Toffoli | 111 > =
 [[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]]
